# Generated by Django 3.0.7 on 2020-08-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0002_auto_20200718_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktailrecipe',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cocktailrecipe',
            name='tag',
            field=models.CharField(blank=True, default='', max_length=30),
            preserve_default=False,
        ),
    ]
