# Generated by Django 3.0.7 on 2020-06-27 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_postcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcomment',
            old_name='comment',
            new_name='comment_detail',
        ),
        migrations.RenameField(
            model_name='postcomment',
            old_name='commenter',
            new_name='user',
        ),
    ]
