# Generated by Django 3.0.7 on 2020-07-10 15:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0005_auto_20200629_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=models.SET('Anonymous'), to=settings.AUTH_USER_MODEL),
        ),
    ]
